basePath: /api
definitions:
  models.Plan:
    properties:
      feature_amount_image_to_prompt:
        description: TODO https://replicate.com/methexis-inc/img2prompt
        type: integer
      feature_amount_images:
        type: integer
      id:
        type: integer
      is_init:
        type: boolean
      plan_description:
        type: string
      plan_name:
        type: string
      price:
        type: integer
    type: object
  models.VersionExtendedInfo:
    properties:
      feature_amount_image_to_prompt:
        description: TODO https://replicate.com/methexis-inc/img2prompt
        type: integer
      feature_amount_images:
        type: integer
      total_image_count:
        type: integer
      version_id:
        type: string
    type: object
  payments.AvailablePlansResponse:
    properties:
      code:
        type: integer
      plans:
        items:
          $ref: '#/definitions/models.Plan'
        type: array
    type: object
  payments.CreatePaymentLinkRequest:
    properties:
      plan_id:
        type: integer
      promocode_id:
        type: string
      version_id:
        type: string
    type: object
  payments.CreatePaymentLinkResponse:
    properties:
      code:
        type: integer
      url:
        type: string
    type: object
  prompts.CreatePromptRequest:
    properties:
      amount_images:
        type: integer
      negative_prompt:
        type: string
      prompt:
        type: string
    type: object
  versions.TrainVersionResponse:
    properties:
      code:
        type: integer
      message:
        type: string
      version_id:
        type: string
    type: object
  versions.VersionInfoResponse:
    properties:
      code:
        type: integer
      info:
        $ref: '#/definitions/models.VersionExtendedInfo'
      is_ready:
        type: boolean
      time_training:
        type: string
    type: object
info:
  contact: {}
  title: API
  version: "1.0"
paths:
  /v1/payments/create:
    post:
      consumes:
      - application/json
      description: Create payment link
      parameters:
      - description: Payment data
        in: body
        name: payment_data
        required: true
        schema:
          $ref: '#/definitions/payments.CreatePaymentLinkRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/payments.CreatePaymentLinkResponse'
      summary: Create payment link
      tags:
      - payments
  /v1/payments/plans/list:
    get:
      description: List available plans
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/payments.AvailablePlansResponse'
      summary: List available plans
      tags:
      - payments
  /v1/payments/webhook:
    post:
      consumes:
      - application/json
      description: Webhook for stripe
      parameters:
      - description: Payment data
        in: body
        name: payment_data
        required: true
        schema:
          $ref: '#/definitions/payments.CreatePaymentLinkRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/payments.CreatePaymentLinkResponse'
      summary: Webhook for stripe
      tags:
      - payments
  /v1/prompts/create/{id}:
    post:
      consumes:
      - application/json
      description: Start prediction for prompt
      parameters:
      - description: Version ID
        in: path
        name: id
        required: true
        type: string
      - description: Prompt data
        in: body
        name: prompt_data
        required: true
        schema:
          $ref: '#/definitions/prompts.CreatePromptRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/prompts.CreatePromptRequest'
      summary: Start prediction for prompt
      tags:
      - prompts
  /v1/prompts/list/{id}:
    get:
      consumes:
      - application/json
      description: Returns prompts and images for version
      parameters:
      - description: Version ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/prompts.CreatePromptRequest'
      summary: Returns prompts and images for version
      tags:
      - prompts
  /v1/versions/info/{id}:
    get:
      description: Get info about version
      parameters:
      - description: Version ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/versions.VersionInfoResponse'
      summary: Get info about version
      tags:
      - versions
  /v1/versions/train/{id}:
    post:
      consumes:
      - multipart/form-data
      description: Start training process
      parameters:
      - description: Class name
        in: query
        name: class
        required: true
        type: string
      - description: Payment ID
        in: path
        name: id
        required: true
        type: string
      - description: Data
        in: formData
        items:
          type: file
        name: data
        required: true
        type: array
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/versions.TrainVersionResponse'
      summary: Start training process
      tags:
      - versions
swagger: "2.0"
