version: '3.7'

x-base: &base
    env_file:
        - .env

services:
    postgres:
        <<: *base
        image: postgres:13
        hostname: postgres
        restart: always
        ports:
            - ${POSTGRES_LOCAL_PORT}:5432
        volumes:
            - ./data/postgres:/var/lib/postgresql/data

    redis:
        image: redis
        restart: always
        ports:
            - 127.0.0.1:${REDIS_LOCAL_PORT}:6379
        volumes:
            - ./data/redis:/data

    api:
        <<: *base
        restart: always
        build:
            context: .
            dockerfile: src/services/api/Dockerfile
        ports:
            - 127.0.0.1:${API_PORT}:${API_PORT}
            - "127.0.0.1:7100:7100"
        depends_on:
            - postgres
            - redis

    imager:
        <<: *base
        restart: always
        build:
            context: .
            dockerfile: src/services/imager/Dockerfile
        ports:
            - 127.0.0.1:${IMAGER_PORT}:${IMAGER_PORT}
        depends_on:
            - postgres
            - redis

    cron:
        <<: *base
        restart: always
        build:
            context: .
            dockerfile: src/services/cron/Dockerfile
        depends_on:
            - postgres
            - redis

    ####################### MONITORING #######################
    prometheus:
        restart: always
        image: prom/prometheus:latest
        user: root
        volumes:
            - ./prometheus.yaml:/etc/prometheus/prometheus.yml
            - ./data/prometheus:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--storage.tsdb.retention.time=365h'
        ports:
            - 127.0.0.1:${PROMETHEUS_LOCAL_PORT}:9090

    grafana:
        restart: always
        image: grafana/grafana
        user: root
        volumes:
            - ./data/grafana:/var/lib/grafana
        ports:
            - 127.0.0.1:${GRAFANA_LOCAL_PORT}:3000

    node-exporter:
        image: prom/node-exporter:latest
        restart: unless-stopped
        ports:
            - 127.0.0.1:${NODE_EXPORT_LOCAL_PORT}:9100
