version: '3.7'

x-base: &base
    env_file:
        - .env

services:
    postgres:
        <<: *base
        image: postgres:13
        hostname: postgres
        restart: always
        ports:
            - ${POSTGRES_LOCAL_PORT}:5432
        volumes:
            - ./data/postgres:/var/lib/postgresql/data

    redis:
        image: redis
        restart: always
        ports:
            - 127.0.0.1:${REDIS_LOCAL_PORT}:6379
        volumes:
            - ./data/redis:/data
