global:
    scrape_interval: 15s
    external_labels:
        monitor: 'ecomdream-monitor'

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: ['localhost:9090']

    - job_name: 'api'
      static_configs:
          - targets: ['api:7100']

    - job_name: 'node'
      static_configs:
          - targets: ['node-exporter:9100']
